
const ACTION_TYPES = {
    FETCH_READING_LIST:  "FETCH_MY_READING_LIST",
    ADD_TO_READING_LIST:  "ADD_TO_READING_LIST",
    REMOVE_READING_LIST:  "REMOVE_READING_LIST",
    FETCH_CATEGORIES:  "FETCH_CATEGORIES",
    ADD_CATEGORY:  "ADD_CATEGORY",
    REMOVE_CATEGORY:  "REMOVE_CATEGORY",
    UPDATE_CATEGORY:  "UPDATE_CATEGORY",
}

export default ACTION_TYPES